# Generated by Django 5.2.12 on 2026-04-06 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessaoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "fundo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("data_abertura", models.DateTimeField(auto_now_add=True)),
                ("data_fechamento", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ABERTA", "Aberta"), ("FECHADA", "Fechada")],
                        default="ABERTA",
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "operador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ABERTO", "Em Aberto"),
                            ("FINALIZADA", "Finalizada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="EM_ABERTO",
                        max_length=12,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("nf_emitida", models.BooleanField(default=False)),
                ("nf_numero", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vendas.sessaocaixa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produtos.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="vendas.venda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendaPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "forma",
                    models.CharField(
                        choices=[
                            ("DINHEIRO", "Dinheiro"),
                            ("CARTAO_DEBITO", "Cartão Débito"),
                            ("CARTAO_CREDITO", "Cartão Crédito"),
                            ("PIX", "Pix"),
                            ("FIADO", "Fiado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="vendas.venda",
                    ),
                ),
            ],
        ),
    ]
