# Generated by Django 5.2.12 on 2026-04-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_fix_base_model_vendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='nf_emitida',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='nf_numero',
        ),
    ]
