# Generated by Django 5.2.12 on 2026-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0004_remove_venda_nf_emitida_remove_venda_nf_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="nf_chave",
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="nf_emitida",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venda",
            name="nf_numero",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="nf_recibo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="nf_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="nf_url_pdf",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
