# Generated by Django 5.2.12 on 2026-04-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0005_venda_nf_chave_venda_nf_emitida_venda_nf_numero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="nf_serie",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
