# Generated by Django 5.2.12 on 2026-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0006_venda_nf_serie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venda",
            old_name="nf_recibo",
            new_name="nf_protocolo",
        ),
        migrations.AddField(
            model_name="venda",
            name="nf_id_fiscal",
            field=models.UUIDField(
                blank=True, help_text="ID interno do Bridge", null=True
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="nf_mensagem",
            field=models.TextField(
                blank=True, help_text="Mensagem de retorno da SEFAZ", null=True
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="nf_qr_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
