# Generated by Django 5.2.12 on 2026-04-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0007_rename_nf_recibo_venda_nf_protocolo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="nf_tipo",
            field=models.CharField(
                choices=[("nfce", "NFC-e"), ("nfe", "NF-e")],
                default="nfce",
                help_text="Modelo do documento (65 ou 55)",
                max_length=5,
            ),
        ),
    ]
