# Generated by Django 5.2.12 on 2026-04-24 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_venda_nf_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacaocaixa',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='vendapagamento',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
