# Generated by Django 5.2.12 on 2026-04-24 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_operacaocaixa_id_externo_sessaocaixa_id_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacaocaixa',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sessaocaixa',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendapagamento',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
