# Generated by Django 5.2.12 on 2026-07-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0010_alter_operacaocaixa_id_externo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ABERTO", "Em Aberto"),
                    ("FINALIZADA", "Finalizada"),
                    ("CANCELADA", "Cancelada"),
                    ("ORCAMENTO", "Orçamento"),
                ],
                default="EM_ABERTO",
                max_length=12,
            ),
        ),
    ]
