# Generated by Django 5.2.12 on 2026-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "codigo_legado",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("razao_social", models.CharField(blank=True, max_length=255)),
                ("nome", models.CharField(max_length=255)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("uf", models.CharField(blank=True, max_length=2, null=True)),
                ("cep", models.CharField(blank=True, max_length=10, null=True)),
                ("telefone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("cpf_cnpj", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "inscricao_estadual",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "pessoa",
                    models.CharField(
                        choices=[("F", "Física"), ("J", "Jurídica")],
                        default="F",
                        max_length=1,
                    ),
                ),
                ("regime_tributario", models.IntegerField(default=0)),
                (
                    "tipo_cliente",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_cadastro", models.DateTimeField(blank=True, null=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                (
                    "limite_credito",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_aberto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("loja", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
