# Generated by Django 5.2.12 on 2026-04-24 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
