# Generated by Django 5.2.12 on 2026-04-24 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_id_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
