# Generated by Django 5.2.12 on 2026-04-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_fix_base_model_financeiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="contapagar",
            name="data_fim_recorrencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contapagar",
            name="parcela_atual",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="contapagar",
            name="proxima_recorrencia",
            field=models.DateField(
                blank=True, help_text="Usado internamente para controle", null=True
            ),
        ),
        migrations.AddField(
            model_name="contapagar",
            name="recorrente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="data_fim_recorrencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="parcela_atual",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="proxima_recorrencia",
            field=models.DateField(
                blank=True, help_text="Usado internamente para controle", null=True
            ),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="recorrente",
            field=models.BooleanField(default=False),
        ),
    ]
