# Generated by Django 5.2.12 on 2026-04-24 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contapagar_data_fim_recorrencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanceira',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
