# Generated by Django 5.2.12 on 2026-04-24 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_categoriafinanceira_id_externo_contapagar_id_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriafinanceira',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
