# Generated by Django 5.2.12 on 2026-06-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0005_alter_categoriafinanceira_id_externo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contapagar",
            name="conta",
            field=models.CharField(
                choices=[("EMPRESA", "Empresa"), ("PESSOAL", "Pessoal")],
                default="EMPRESA",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contareceber",
            name="conta",
            field=models.CharField(
                choices=[("EMPRESA", "Empresa"), ("PESSOAL", "Pessoal")],
                default="EMPRESA",
                max_length=10,
            ),
        ),
    ]
