# Generated by Django 5.2.12 on 2026-04-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "codigo_legado",
                    models.IntegerField(
                        blank=True,
                        help_text="Código da Mercadoria no sistema legado",
                        null=True,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "codigo_barras",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preco_compra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "preco_venda",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unidade_medida", models.CharField(default="UN", max_length=10)),
                ("grupo", models.CharField(blank=True, max_length=100, null=True)),
                ("subgrupo", models.CharField(blank=True, max_length=100, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("ncm", models.CharField(blank=True, max_length=10, null=True)),
                ("cest", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "origem",
                    models.CharField(
                        default="0",
                        help_text="Origem da mercadoria (0 - Nacional, etc)",
                        max_length=2,
                    ),
                ),
                ("cfop_padrao", models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EstoqueLoja",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("loja", models.CharField(max_length=100)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "unique_together": {("produto", "loja")},
            },
        ),
    ]
