# Generated by Django 5.2.12 on 2026-04-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoEstoque",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")],
                        max_length=10,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("VENDA", "Venda"),
                            ("COMPRA", "Compra"),
                            ("AJUSTE", "Ajuste Manual"),
                            ("DEVOLUCAO", "Devolução"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "saldo_anterior",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "saldo_atual",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
