# Generated by Django 5.2.12 on 2026-04-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0004_grupo_alter_estoqueloja_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grupo",
            options={
                "ordering": ["nome"],
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
            },
        ),
    ]
