# Generated by Django 5.2.12 on 2026-04-24 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_grupo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueloja',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
