# Generated by Django 5.2.12 on 2026-04-24 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_estoqueloja_id_externo_grupo_id_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueloja',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
