# Generated by Django 5.2.12 on 2026-04-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaFiscalEmitida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("NFE", "NF-e"), ("NFSE", "NFS-e"), ("NFCE", "NFC-e")],
                        default="NFE",
                        max_length=5,
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=20)),
                (
                    "chave_acesso",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("xml", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EMITIDA", "Emitida"),
                            ("CANCELADA", "Cancelada"),
                            ("REJEITADA", "Rejeitada"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                ("destinatario_nome", models.CharField(blank=True, max_length=255)),
                ("destinatario_cpf_cnpj", models.CharField(blank=True, max_length=20)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "api_reference",
                    models.CharField(
                        blank=True,
                        help_text="Referência da API Focus NFe",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("emitida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "enviado_contador",
                    models.BooleanField(
                        default=False, help_text="XML enviado ao contador"
                    ),
                ),
                ("data_envio_contador", models.DateTimeField(blank=True, null=True)),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendas.venda",
                    ),
                ),
            ],
        ),
    ]
