# Generated by Django 5.2.12 on 2026-04-08 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0001_initial"),
        ("vendas", "0003_fix_base_model_vendas"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFCe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ref", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "chave_nfe",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                ("serie", models.CharField(blank=True, max_length=5, null=True)),
                ("protocolo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("autorizado", "Autorizado"),
                            ("erro_autorizacao", "Erro de Autorização"),
                            ("cancelado", "Cancelado"),
                            ("denegado", "Denegado"),
                            ("contingencia", "Contingência Offline"),
                        ],
                        default="pendente",
                        max_length=30,
                    ),
                ),
                (
                    "status_sefaz",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("mensagem_sefaz", models.TextField(blank=True, null=True)),
                ("cnpj_emitente", models.CharField(max_length=14)),
                ("caminho_xml", models.TextField(blank=True, null=True)),
                ("caminho_danfe", models.TextField(blank=True, null=True)),
                ("caminho_xml_cancelamento", models.TextField(blank=True, null=True)),
                ("qrcode_url", models.TextField(blank=True, null=True)),
                ("url_consulta_nf", models.TextField(blank=True, null=True)),
                ("contingencia_offline", models.BooleanField(default=False)),
                ("contingencia_offline_efetivada", models.BooleanField(default=False)),
                ("payload_enviado", models.JSONField(blank=True, null=True)),
                ("resposta_focusnfe", models.JSONField(blank=True, null=True)),
                ("justificativa_cancelamento", models.TextField(blank=True, null=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vendas.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "NFC-e",
                "verbose_name_plural": "NFC-es",
                "indexes": [
                    models.Index(
                        fields=["status", "is_deleted"],
                        name="fiscal_nfce_status_34e3f3_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="fiscal_nfce_created_ecb4cc_idx"
                    ),
                    models.Index(
                        fields=["cnpj_emitente", "status"],
                        name="fiscal_nfce_cnpj_em_07ecdd_idx",
                    ),
                ],
            },
        ),
    ]
