# Generated by Django 5.2.12 on 2026-04-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0003_nfe"),
        ("vendas", "0003_fix_base_model_vendas"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfe",
            name="cnpj_destinatario",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="nfe",
            name="cpf_destinatario",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="nfe",
            name="finalidade_emissao",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="nfe",
            name="nome_destinatario",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nfe",
            name="tentativas_consulta",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nfe",
            name="tipo_documento",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="nfe",
            name="ultima_consulta_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nfe",
            name="valor_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nfe",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("processando_autorizacao", "Processando Autorização"),
                    ("autorizado", "Autorizado"),
                    ("erro_autorizacao", "Erro de Autorização"),
                    ("cancelado", "Cancelado"),
                    ("denegado", "Denegado"),
                ],
                db_index=True,
                default="pendente",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="nfe",
            index=models.Index(
                fields=["cnpj_emitente", "status"], name="fiscal_nfe_cnpj_em_a6fc0e_idx"
            ),
        ),
    ]
