# Generated by Django 5.2.12 on 2026-04-08 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0002_fix_base_model_compras"),
        ("fiscal", "0004_nfe_cnpj_destinatario_nfe_cpf_destinatario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFeRecebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "chave_nfe",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("nome_emitente", models.CharField(max_length=255)),
                ("documento_emitente", models.CharField(max_length=20)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_emissao", models.DateTimeField()),
                ("situacao", models.CharField(max_length=20)),
                (
                    "manifestacao_destinatario",
                    models.CharField(
                        choices=[
                            ("nulo", "Não Manifestada"),
                            ("ciencia", "Ciência da Operação"),
                            ("confirmacao", "Confirmação da Operação"),
                            ("desconhecimento", "Desconhecimento da Operação"),
                            ("nao_realizada", "Operação não Realizada"),
                        ],
                        default="nulo",
                        max_length=20,
                    ),
                ),
                (
                    "versao",
                    models.IntegerField(
                        help_text="Versão do documento na Focus NFe para controle de sincronização"
                    ),
                ),
                ("xml_completo", models.TextField(blank=True, null=True)),
                ("nfe_completa", models.BooleanField(default=False)),
                (
                    "nota_compra",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfe_recebida",
                        to="compras.notacompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "NF-e Recebida",
                "verbose_name_plural": "NF-es Recebidas",
                "ordering": ["-data_emissao"],
                "indexes": [
                    models.Index(
                        fields=["chave_nfe"], name="fiscal_nfer_chave_n_1e24b9_idx"
                    ),
                    models.Index(
                        fields=["documento_emitente"],
                        name="fiscal_nfer_documen_c32eb6_idx",
                    ),
                ],
            },
        ),
    ]
