# Generated by Django 5.2.12 on 2026-04-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("numero_nf", models.CharField(blank=True, max_length=50)),
                ("fornecedor", models.CharField(max_length=255)),
                ("cnpj_fornecedor", models.CharField(blank=True, max_length=20)),
                ("data_emissao", models.DateField(blank=True, null=True)),
                ("data_entrada", models.DateField(auto_now_add=True)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("RECEBIDA", "Recebida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                (
                    "xml_nfe",
                    models.TextField(
                        blank=True,
                        help_text="XML da NF-e (integração futura)",
                        null=True,
                    ),
                ),
                (
                    "chave_acesso",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "api_source",
                    models.CharField(
                        blank=True,
                        help_text="Fonte da API (uso futuro)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemNotaCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("descricao", models.CharField(max_length=255)),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produtos.produto",
                    ),
                ),
                (
                    "nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="compras.notacompra",
                    ),
                ),
            ],
        ),
    ]
