# Generated by Django 5.2.12 on 2026-04-24 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_fix_base_model_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotacompra',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='notacompra',
            name='id_externo',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='notacompra',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
