# Generated by Django 5.2.12 on 2026-04-24 07:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_itemnotacompra_id_externo_notacompra_id_externo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnotacompra',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='notacompra',
            name='id_externo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
